services:
  - type: web
    name: mr-helper
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
    envVars:
      - key: DATABASE_URL
        value: your-supabase-or-postgres-database-url
